CREATE USER 'LaravelDB'@'localhost' IDENTIFIED BY  'mypass';

GRANT USAGE ON * . * TO  'LaravelDB'@'localhost' IDENTIFIED BY  'mypass' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

CREATE DATABASE IF NOT EXISTS  `LaravelDB` ;

GRANT ALL PRIVILEGES ON  `LaravelDB` . * TO  'LaravelDB'@'localhost';